export const BOOK = {
  home: '/',
  war: '/war',
  warConsequences: '/war-consequences',
  safeCity: '/safe-city',
  cityCulture: '/city-culture',
  charity: '/charity',
  heraldChim: '/herald-chim',
  educationalPrograms: '/educational-programs',
  reports: '/reports',
  fpvSchool: '/fpv-school',
  fpvMaster: '/fpv-master',
  civilTraining: '/civil-training',
  citizensCulture: '/citizens-culture',
  IPSOlogy: '/ipsology',
};
